[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npm run build"]

[phases.start]
cmds = ["npm start"]

[build]
ignore = ["dist/"]  # 🔥 This line prevents Railway from deleting your build output!
